service: nest-serverless-framework-demo
plugins:
  - serverless-offline
  - serverless-step-functions
provider:
  name: aws
  runtime: nodejs12.x
functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: any
          path: /
  stepFunctions:
    ${file(src/step-functions/test-step-function/function.yml)}
stepFunctions:
  stateMachines:
    testStepFunction:
      ${file(src/step-functions/test-step-function/definition.yml)}